# Generated by Django 4.1 on 2022-08-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricsoftener',
            name='price',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='fabricsoftener',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
