# Generated by Django 4.1 on 2022-08-26 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_fabricsoftener_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=50)),
                ('proof_id', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=40)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
