# Generated by Django 4.1 on 2022-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_traders'),
    ]

    operations = [
        migrations.AddField(
            model_name='traders',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
