# Generated by Django 4.1 on 2022-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_traders_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='profile_picture',
            field=models.CharField(max_length=2083),
        ),
    ]
