# Generated by Django 4.1 on 2022-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_traders_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
