# Generated by Django 4.1 on 2022-12-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_traders_name_alter_traders_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
