# Generated by Django 4.1 on 2022-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_traders_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricsoftener',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
