# Generated by Django 4.1 on 2022-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_fabricsoftener_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricsoftener',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
