# Generated by Django 4.1 on 2022-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_fabricsoftener_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traders',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
