# Generated by Django 4.1 on 2022-12-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_fabricsoftener_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricsoftener',
            name='product_volume',
            field=models.CharField(default='500ML', max_length=10),
        ),
        migrations.AlterField(
            model_name='fabricsoftener',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
